name: Continuous Integration & Deployment
on:
  push:
    tags:
      - v*

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: frabert/replace-string-action@v2.0
        id: get-version-from-tag
        with:
          pattern: v(.*)
          string: ${{ github.ref_name }}
          replace-with: $1

      - uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Version ${{ steps.get-version-from-tag.outputs.replaced }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      version: ${{ steps.get-version-from-tag.outputs.replaced }}

  deploy-site:
    name: Deploy site
    runs-on: ubuntu-latest
    needs: create-release
    concurrency:
      group: ${{ github.workflow }}-deploy-site
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: "@agusmgarcia"

      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: npm run build
        env:
          NEXT_PUBLIC_APP_VERSION: ${{ needs.create-release.outputs.version }}

      - uses: w9jds/firebase-action@v2.1.2
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
