name: Continuous Integration & Deployment
on:
  push:
    tags:
      - v*

jobs:
  deploy-app:
    name: Deploy application
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-deploy-app
      cancel-in-progress: true

    steps:
      - uses: agusmgarcia/github-deploy-app@v1.0.4
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
