name: Continuous Integration & Deployment
permissions: write-all
on:
  push:
    tags:
      - v*

jobs:
  deploy-app:
    name: Deploy application
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-deploy-app
      cancel-in-progress: true

    steps:
      - uses: agusmgarcia/github-actions/deploy-app@v1.1.0
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
