name: Deploy site
on:
  release:
    types: [created]

jobs:
  deploy-site:
    name: Deploy site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
          cache: npm
          registry-url: "https://npm.pkg.github.com"
          scope: "@agusmgarcia"

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: npm run build

      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
